### ISSUE TITLE
README should show how to use easy_roles in Rails 3 correctly

### ISSUE THREAD

**Issue by programatt** [platform45/easy_roles#10]
Readme should be updated to show how to use easy_roles with the gemfile in rails 3.

`gem 'easy_roles', :require => 'easy_roles', :git => 'git@github.com/platform45/easy_roles/easy_roles.git'` for example

**Comment by ryanza** [comment]
There are new versions of Easy Roles - Please use the following for the latest rewrite - Rails 3.x support only!

``` ruby
gem 'easy_roles', '2.0.0.beta2'
```
