### ISSUE TITLE
Deprecation warning, Rails 3 compatibility.

### ISSUE THREAD

**Issue by serek** [platform45/easy_roles#11]
Hello Ryan,

Just wanted to ask when You will drop out Rails2 compatibility because I would gladly start using Your gem again, not some forks with links to their github repo.

Best,
M

**Comment by ryanza** [comment]
Will work on it tonight. It's about time..

**Comment by serek** [comment]
Especially when You only need to use code from one of Your forks :) these guys has already done it :)

Best!
