### ISSUE TITLE
Branch for Rails 3

### ISSUE THREAD

**Issue by aarona** [platform45/easy_roles#13]
This is an easy one actually. Take kdaigle's fork (only one change) and make a rails 3 branch from it. He fixes the DEPRECATION notice regarding before_validation.

See this: https://github.com/kdaigle/easy_roles/commit/1ed2bbea3fc2fbef63a8ab410b93978d2465c13f

**Comment by ryanza** [comment]
There are new versions of Easy Roles - Please use the following for the latest rewrite - Rails 3.x support only!

``` ruby
gem 'easy_roles', '2.0.0.beta2'
```
