### ISSUE TITLE
please add  with_role scope

### ISSUE THREAD

**Issue by vkill** [platform45/easy_roles#14]
http://asciicasts.com/episodes/189-embedded-association

**Comment by danman01** [comment]
The with_role scope is added, but it isn't working out of the box for me. I copied the scope into my user model and replaced column name with my column name.

**Comment by miraclecoder** [comment]
this works for me:

scope :with_role, proc { |r|
          query = "#{self.table_name}.roles LIKE " + ['\'%',r,'%\''].join
          where(query)
                         }

**Comment by asgeo1** [comment]
+1

I couldn't see anywhere in the source code where the `with_role` scope was added, even though the documentation suggests that `with_role` does work. Please add this in!
