### ISSUE TITLE
Roles duplication

### ISSUE THREAD

**Issue by serek** [platform45/easy_roles#2]
Hello,

We should not be able to add existing role to user roles.

Example:
    @u = User.first
    @u.add_role 'admin'
    @u.save

```
@u.roles => ['admin']
```

And now when adding more roles
    @u.add_role 'admin'
    @u.save

```
@u.roles => ['admin','admin']
```

It should not add same role to user.

**Comment by neilh** [comment]
You're right. Will fix that ASAP.

**Comment by ryanza** [comment]
Yeah, good idea. Implementing it as we speak..

**Comment by serek** [comment]
It also would be nice to compile new gem version :)

**Comment by ryanza** [comment]
It has been. Version 0.4.2 :)

**Comment by neilh** [comment]
http://gemcutter.org/gems/easy_roles/versions/0.4.2

**Comment by serek** [comment]
Thanks, I didn't spot that. I'm already at the newest version ;)
