### ISSUE TITLE
Migration file is generated without `.rb` extension

### ISSUE THREAD

**Issue by x-ji** [platform45/easy_roles#22]
`20150309134233_add_easy_roles_to_users` is generated instead of `20150309134233_add_easy_roles_to_users.rb`. I ran `rake db:migrate` without realizing the issue, the column was of course not added, and it took a while for me to debug.

**Comment by being-frank** [comment]
Hi @x-ji 

Unfortunately, this project is no longer being maintained. I apologise for any inconvenience this may have caused you.
