### ISSUE TITLE
undefined method `before_validation_on_create' on Rails 3.0.0.beta2

### ISSUE THREAD

**Issue by firebelly** [platform45/easy_roles#3]
I created a rails3 [branch](http://github.com/firebelly/easy_roles/tree/rails3) in my fork, [patched](http://github.com/firebelly/easy_roles/commit/6ef962211c16357f0febd9ea996ec529e5ae4db3) it and sent a pull request.

I wasn't able to use it as a gem in my fork with:

`gem 'easy_roles', :git => "git://github.com/firebelly/easy_roles.git", :branch => "rails3"`

I think because it doesn't have a `.gemspec` file checked into the repository?

In the meantime you can install it as plugin in like so:

`rails plugin install git://github.com/firebelly/easy_roles.git -r rails3`

Then put `require easy_roles` in your `environment.rb` file.

**Comment by ryanza** [comment]
Hey,

I just fixed this in Version 1.0.0 of easy_roles. Thanks for this, we haven't moved to Rails 3 yet, so I haven't had time to test easy_roles in it. (This is why I must write the tests ASAP!)

Thanks for this,

Ryan
