### ISSUE TITLE
Rails 3 Deprecation Warning

### ISSUE THREAD

**Issue by MikeBinstock** [platform45/easy_roles#5]
DEPRECATION WARNING: before_validation_on_create is deprecated. Please use before_validation(arguments, :on => :create. (called from easy_roles at /Users/Pibefision/.rvm/gems/ruby-1.9.2-p0/gems/easy_roles-1.0.0/lib/easy_roles.rb:14)

**Comment by ryanza** [comment]
Hey,

Going to get on this now.

**Comment by MikeBinstock** [comment]
Thank you master!!! :)

**Comment by MikeBinstock** [comment]
I'm still getting this

DEPRECATION WARNING: before_validation_on_create is deprecated. Please use before_validation(arguments, :on => :create. (called from class:User at /Users/Pibefision/Documents/Proyectos/ideagoras/app/models/user.rb:7)
