### ISSUE TITLE
Get error when issuing is_xxx? on user model fetched via association

### ISSUE THREAD

**Issue by makuchaku** [platform45/easy_roles#6]
## Partner.last.user.class ==> User (a valid object on which I can perform all operations)

> > Partner.last.user.is_partner?
> > NoMethodError: undefined method `is_user?' for #ActiveRecord::Associations::BelongsToAssociation:0x7f75edc959e0

However, when I do
u = User.last
u.is_partner?

> > true

Thanks

**Comment by ryanza** [comment]
Hey,

It seems that Partner.last.user is returning ActiveRecord::Associations::BelongsToAssociation class instead of User class, which is why the method does not exist. I'll look into this.

**Comment by ryanza** [comment]
What version of rails are you running?

**Comment by makuchaku** [comment]
I'm using Rails 2.3.5

**Comment by makuchaku** [comment]
The returned class seems to be correct...

> > Partner.last.user.class
> > => User

**Comment by ryanza** [comment]
Ok found the error, will release the new gem soon. Thanks!

**Comment by ryanza** [comment]
Ok the fix has just been pushed up - Version 1.1.0 - Thanks!

**Comment by makuchaku** [comment]
Awesome, thanks!
Checking the fix...

**Comment by makuchaku** [comment]
Fix is confirmed.
Great work :)

**Comment by ryanza** [comment]
Awesome, no problem :)
