### ISSUE TITLE
deprec warning on rails 3

### ISSUE THREAD

**Issue by MikeBinstock** [platform45/easy_roles#7]
DEPRECATION WARNING: before_validation_on_create is deprecated. Please use before_validation(arguments, :on => :create. (called from class:User a

**Comment by ryanza** [comment]
Hey,

This occurs because the current setup for easy_roles is that it can work on Rails 2 and Rails 3, I will remove Rails 2 compatibility soon, then this warning will disappear. Thanks for reporting it :)

**Comment by MikeBinstock** [comment]
thanks!

**Comment by bitboxer** [comment]
Isn't it time to remove this :) ?

**Comment by ryanza** [comment]
The next version of the gem will be Rails 3 Only :)
