### ISSUE TITLE
Generator not found using Rails 3

### ISSUE THREAD

**Issue by bitboxer** [platform45/easy_roles#9]
When using Rails 3 the generator is not found and I have to add the roles field myselfs

**Comment by tallica** [comment]
I can confirm that too. I use Ruby 1.9.2p0 with Rails 3.0.3 and easy_roles 1.1.0.

**Comment by bluntpeak** [comment]
Same here 1.9.2p0 rails 3.0.5 latest git easy_roles

**Comment by bluntpeak** [comment]
Almost have new rails 3 generators working...

**Comment by ryanza** [comment]
There are new versions of Easy Roles - Please use the following for the latest rewrite - Rails 3.x support only!

``` ruby
gem 'easy_roles', '2.0.0.beta2'
```
